# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    analysis = stats.zanomaly("network_bytes_transferred")
    session.set("anomalies", [analysis])
    return "Initialized zanomaly detection"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return "fortigate_network_traffic_anomaly_detection"

def automate():

    # automation: fortigate_network_traffic_anomaly_detection
    return True

def notify():
    return False

def algorithm(event):

    destination_ip = event.get("destination_ip")
    destination_ports = ["23", "22", "3389"]
    application_protocols = ["ICMP", "TELNET", "SSH", "RDP"]
    account_name = event.get("user_name")

    total_bytes = int(event.get("network_bytes_transferred") or 0)

    if not destination_ip or total_bytes <= 0:
        return 0.0
    cidranges=[] # put cidr ranges
    in_range = cidr.inRange(destination_ip, cidranges)

    condition1 = (
        event.get("destination_port") == "53"
        or (
            event.get("network_protocol") is not None
            and (
                "HTTP" in str(event.get("network_protocol")).upper()
                or "HTTPS" in str(event.get("network_protocol")).upper()
            )
        )
    )

    condition2 = (
        event.get("destination_port") in destination_ports
        or str(event.get("network_protocol") or "").upper() in application_protocols
    ) and (
        account_name is not None
        and account_name not in ["-", "UNKNOWN", ""]
        and "$" not in str(account_name)
    )

    final_condition = condition1 or condition2

    if final_condition:
        stats.count("abnormal")
        count = stats.getcount("abnormal")

        analysis = session.get("anomalies")[0]
        anomaly = analysis.get("anomaly")

        if in_range and count >= 25 and anomaly == 1:
            stats.resetcount("abnormal")
            return 0.75

    return 0.0


def clusters(event):





    return session.get("anomalies")

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    analysis = session.get("anomalies")[0]
    mean = analysis.get("mean")

    return (
        "Abnormal volume of data was transmitted from source IP "
        + str(event.get("source_ip") or "Unknown")
        + " to destination "
        + str(event.get("destination_ip") or "Unknown")
        + " within the monitored CIDR range over port "
        + str(event.get("destination_port") or "Unknown")
        + " using protocol "
        + str(event.get("network_protocol") or "Unknown")
        + ". Total bytes transferred: "
        + str(event.get("network_bytes_transferred") or 0)
        + ", which is anomalous compared to the learned baseline mean of "
        + str(mean)
        + " bytes. This may indicate lateral movement, internal staging, unauthorized bulk transfer, or misuse of trusted network paths."
    )

def criticality():
    return "HIGH"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Alternative Protocol (T1048)"

def artifacts():
    return stats.collect(["source_ip","network_protocol","network_bytes_out","network_bytes_in","destination_ip","destination_country"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
