
# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    analysis = stats.zanomaly('network_bytes_out')
    session.set("anomalies", [analysis])
    return "Initialized zanomaly detection"

def window():
    return "30d"

def groupby():
    return ["source_ip","destination_ip"]

def investigate():
    return "palo_alto_network_traffic_intelligence"

def automate():

    # automation: palo_alto_network_traffic_intelligence
    return True

def notify():
    return False

def algorithm(event):
    bytes_out = event.get('network_bytes_out')
    src_ip = event.get('source_ip')
    dst_ip = event.get('destination_ip')

    if not bytes_out or not dst_ip or not src_ip:
        return 0.0
    if _is_internal_ip(dst_ip):
        return 0.0

    z = stats.zanomaly("network_bytes_out")


    if z is None:
        return 0.0

    if z.get("anomaly") == 1 or z.get("anomaly") == 1.0:
        print("----zanomaly-----")
        print(z)
        return 0.85

    return 0.0


def clusters(event):










    cluster = session.get("anomalies")[0]
    cluster["unit"] = "bytes"
    return [cluster]

def context(event):
    src = event.get("source_ip", "unknown")
    dst = event.get("destination_ip", "unknown")
    z = stats.zanomaly("network_bytes_out")
    if z is None:
        return (
            "Unusual outbound volume (bytes) for flow %s -> %s compared to recent baseline."
            % (src, dst)
        )
    return (
        "Unusual outbound volume flow from %s to %s where "
        "current value %.0f bytes, window mean %.0f and "
        "z-score %.2f."
        % (
            src,
            dst,
            float(z.get("value", 0) or 0),
            float(z.get("mean", 0) or 0),
            float(z.get("zscore", 0) or 0),
        )
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Network (T1041)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","network_bytes_out","network_protocol","applicationname"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }


def _is_internal_ip(ip):
    cirdrangelsist=[]
    return cidr.inRange(ip,cirdrangelsist )