# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    #Define teh ueba methdo and ist attributes
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    try:
        file_size = int(event.get("file_size", 0))
    except:
        file_size = 0

    if (
        event.get("event_category") == "upload"
        and event.get("threat_name")
        and file_size >= 104857600
    ):
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusters")

def context(event):
        return (
        "Proofpoint detected that user '{0}' uploaded a large file "
        "containing sensitive information. File '{1}' ({2} bytes) "
        "was uploaded to destination '{3}'. The content matched "
        "DLP classifications ({4}). Large transfers of sensitive "
        "data may indicate bulk data exfiltration or unauthorized "
        "sharing of corporate information. Analysts should review "
        "the destination, validate business justification, and "
        "determine whether the transfer was authorized."
    ).format(
        event.get("source_account_name", "unknown"),
        event.get("file_name", "unknown"),
        event.get("file_size", "unknown"),
        event.get("destination_hostname", "unknown"),
        event.get("threat_name", "unknown")
    )

def criticality():
    return "HIGH"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Archive Collected Data (T1560)"

def artifacts():
    return stats.collect(["source_account_name","url","threat_name","file_name","destination_hostname","file_size"])

def correlationArtifacts():
    return ["source_account_name"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_account_name", "unknown"),
        "type": "username"
    }
