# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "10m"

def groupby():
    return ["source_ip"]

def investigate():
    return "palo_alto_threat_intelligence"

def automate():

    # automation: palo_alto_threat_intelligence
    return True

def notify():
    return False

def algorithm(event):
    source_ip = event.get("source_ip")
    key = application.get("pa_threat_activity:" + str(source_ip))
    if key is True:
        return 0.0

    if stats.count("pa_threat_activity") >= 5:
        application.put("pa_threat_activity:" + str(source_ip), True, 86400)
        stats.resetcount("pa_threat_activity")
        return 0.75
    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    src = event.get("source_ip")
    dst = event.get("destination_ip")
    action = event.get("event_action")
    app = event.get("applicationname")
    subtype = event.get("event_subtype")

    return (
        "Source IP '%s' generated multiple(more than 5) threat events within a 10-minute window. "
        "One observed instance includes '%s' action on '%s' traffic targeting destination '%s' "
        "with threat subtype '%s'. "
        "Repeated threat detections from the same source strongly indicate malicious activity, "
        "such as a compromised host, automated attack tool, or persistent exploitation attempts."
    ) % (src, action, app, dst, subtype)

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","event_action","applicationname","event_subtype"])

def correlationArtifacts():
    return ["source_ip","event_action"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
