# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    try:
        session.set("event", event)
        return "initializee"
    except Exception:
        return None

def window():
    return None

def groupby():
    return []

def investigate():
    return None

def automate():

    return False

def notify():
    return False

def algorithm(event):
    alert_name = (event.get("alert_name") or "").lower()
    severity = (event.get("event_severity") or "").lower()

    if alert_name in [
        "shortcut file dropped in startup folder via powershell",
        "[heuristic attribute] access token manipulation"
    ]:
        return 0.0

    if severity == "low":
        return 0.25

    if severity == "informational":
        return 0.25

    if severity == "medium":
        return 0.50

    if severity == "high":
        return 0.75

    if severity == "critical":
        return 1.0

    return 0.50


def clusters(event):
    return []

def context(event):
    desc = event.get("descriptions")

    return desc

def criticality():
    try:
        event = session.get("event")
        severity = (event.get("event_severity"))

        if not severity:
            return "MEDIUM"

        severity = severity.lower()

        if severity == "informational":
            return "LOW"
        elif severity in ["low"]:
            return "LOW"
        elif severity in ["medium"]:
            return "MEDIUM"
        elif severity in ["high"]:
            return "HIGH"
        elif severity in ["critical"]:
            return "CRITICAL"

        return "MEDIUM"
    except Exception:
        return "MEDIUM"

def tactic():
    event = session.get("event")
    return event.get("tactic")

def technique():
    event = session.get("event")
    return event.get("technique")

def artifacts():
    return stats.collect(["host","user_name","source_ip","command_line","parent_command_line","process_name","url","policy_id"])

def correlationArtifacts():
    return ["host"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("host", "unknown"),
        "type": "host"
    }
