# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "15m"

def groupby():
    return ["source_ip"]

def investigate():
    return None

def automate():

    return True

def notify():
    return False

def algorithm(event):
    bytes = event.get("network_bytes_out")
    dst_ip = event.get("destination_ip")

    cidrranges=[]

    incidrrange = cidr.inRange(dst_ip, cidrranges)

    if incidrrange:
        return 0.0

    if bytes > 500000000:
        return 0.50

    return 0.0


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        "Potential data exfiltration activity detected. "
        "Internal source IP " + str(event.get("source_ip")) +
        " transferred a large volume of outbound data ("
        + str(event.get("network_bytes_out")) + " bytes) "
        "to external destination IP " + str(event.get("destination_ip")) +
        " over " + str(event.get("network_protocol")) +
        " on destination port " + str(event.get("destination_port")) + ". "
        "The connection was allowed by policy ID "
        + str(event.get("policy_id")) +
        " on device " + str(event.get("source_device_name")) + ". "
        "This alert triggered because the amount of data sent exceeded the "
        "configured threshold within a 15-minute window and the destination "
        "IP is not part of the trusted cloud destination list, which may "
        "indicate unauthorized data exfiltration."
    )

def criticality():
    return "MEDIUM"

def tactic():
    return "Exfiltration (TA0010)"

def technique():
    return "Exfiltration Over Network (T1041)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","policy_id"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
