DENY_ACTIONS = {"deny", "drop"}

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["source_ip"]

def investigate():
    return "palo_alto_network_traffic_intelligence"

def automate():

    # automation: palo_alto_network_traffic_intelligence
    return True

def notify():
    return False

def algorithm(event):
    try:
        key = application.get("pa_deny_or_drop")
    except Exception:
        key = None

    if key in (True, "true", "True"):
        return 0.0

    if event.get("event_action") not in DENY_ACTIONS:
        return 0.0

    count = stats.count("pa_deny_or_drop")

    if count < 30:
        return 0.0

    # Reset only when threshold reached
    stats.resetcount("pa_deny_or_drop")

    # Avoid duplicate alerts using distributed lock
    if application.putifabsent("pa_deny_or_drop", True, 86400):
        return 0.5

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    src = event.get("source_ip")
    dst = event.get("destination_ip")
    zone_src = event.get("source_zone")
    zone_dst = event.get("destination_zone")
    action = event.get("event_action")

    return (
        "Source IP '%s' from zone '%s' generated a high number of '%s' firewall actions. "
        "One observed attempt targeted destination '%s' in zone '%s'. "
        "This pattern indicates repeated blocked connection attempts, commonly associated with scanning, "
        "brute-force activity, or misconfigured applications."
    ) % (src, zone_src, action, dst, zone_dst)

def criticality():
    return "MEDIUM"

def tactic():
    return "Reconnaissance (TA0043)"

def technique():
    return "Active Scanning (T1595)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","event_action","source_zone","destination_zone","network_protocol"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }

