# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "15m"

def groupby():
    return ["source_ip"]

def investigate():
    return "palo_alto_network_traffic_intelligence"

def automate():

    # automation: palo_alto_network_traffic_intelligence
    return True

def notify():
    return False

def algorithm(event):
    src = event.get("source_ip")
    dst = event.get("destination_ip")
    key = application.get("pa_internal_host_communication:" + str(src))
    if key is True:
        return 0.0

    action = (event.get("event_action") or "").lower()
    if action not in ["allow", "accept", "permit"]:
        return 0.0

    destination_port = event.get("destination_port")
    if destination_port in ["443", "53", "80"]:
        return 0.0

    # Only consider internal → external traffic
    if src and dst:
        if (src.startswith("10.") or src.startswith("192.168.") or src.startswith("172.")):
            if not (dst.startswith("10.") or dst.startswith("192.168.") or dst.startswith("172.")):
                dest_ip = stats.accumulate(['destination_ip'])
                unique_ip = len(dest_ip.get("destination_ip"))
                if unique_ip > 20:
                  application.put("pa_internal_host_communication:" + str(src), True, 86400)
                  stats.dissipate(['destination_ip'])
                  return 0.75

    return 0.0


def clusters(event):

    return session.get("clusters")

def context(event):
    src = event.get("source_ip")
    zone_src = event.get("source_zone")
    sample_dst = event.get("destination_ip")

    return (
        "Internal host '%s' in zone '%s' communicated with a high number of distinct external destination IP addresses "
        "within a 15-minute window. One observed destination was '%s'. "
        "This fan-out pattern may indicate automated scanning, malware activity, botnet communication, "
        "or other abnormal outbound behavior from a potentially compromised host."
    ) % (src, zone_src, sample_dst)

def criticality():
    return "HIGH"

def tactic():
    return "Discovery (TA0007)"

def technique():
    return "Network Service Scanning (T1046)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","event_action","network_protocol"])

def correlationArtifacts():
    return []

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
