# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """

    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "palo_alto_network_traffic_intelligence"

def automate():

    # automation: palo_alto_network_traffic_intelligence
    return True

def notify():
    return False

def algorithm(event):


    app = event.get("applicationname")
    port = event.get("destination_port")
    src = event.get("source_ip")
    dst = event.get("destination_ip")

    if dst == null  : #whitelistdestiantionip
      return 0.0

    if app != "ssl":
      return 0.0

    key = application.get("pa_ssl_traffic_non_std_port:" + str(dst) + ":" + str(port))

    if key is True:
        return 0.0

    allowed_ssl_ports = ["443", "8443", "9443", "465", "636", "993", "995"]

    # Only check internal outbound SSL traffic
    if src and app == "ssl" and port:
        if (src.startswith("10.") or src.startswith("192.168.") or src.startswith("172.")):
            if not (dst.startswith("10.") or dst.startswith("192.168.") or dst.startswith("172.")):
                if port not in allowed_ssl_ports:
                    application.put("pa_ssl_traffic_non_std_port:" + str(dst) + ":" + str(port), True, 86400)
                    return 0.50

    return 0.0


def clusters(event):

    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    src = event.get("source_ip")
    dst = event.get("destination_ip")
    port = event.get("destination_port")
    zone_src = event.get("source_zone")
    zone_dst = event.get("destination_zone")

    return (
        "Internal host '%s' from zone '%s' initiated an SSL/TLS connection to external destination '%s' "
        "on uncommon port '%s' in zone '%s'. This may be legitimate application traffic using TLS on a custom port, "
        "but it can also indicate encrypted tunneling, evasion, or other suspicious outbound communication."
    ) % (src, zone_src, dst, port, zone_dst)

def criticality():
    return "MEDIUM"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Obfuscated/Encrypted Channel (T1573)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","applicationname","source_zone","destination_zone"])

def correlationArtifacts():
    return ["source_ip","source_zone"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_ip", "unknown"),
        "type": "ipaddress"
    }
