# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    """
    Store the session
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return ["source_ip","destination_ip","destination_port"]

def investigate():
    return "fortigate_network_traffic_anomaly_detection"

def automate():

    # automation: fortigate_network_traffic_anomaly_detection
    return True

def notify():
    return False

def algorithm(event):



        src_ip = str(event.get('source_ip') or '')
        dst_ip = str(event.get('destination_ip') or '')
        dst_port = str(event.get('destination_port') or '')
        action = str(event.get('event_action') or '').lower()
        role = str(event.get('destination_device_interface_role') or '').lower()
        protocol = str(event.get('network_protocol') or '').upper()
        direction = (event.get("network_direction")or "").lower()

        if direction and direction != "outbound":
          return 0.0

        if action not in ['accept', 'allow', 'permit']:
            return 0.0

        if role != 'wan':
            return 0.0
        # cidrangeslist=[]
        # incidrrange = cidr.inRange(dst_ip,cidrangeslist )

        # if incidrrange:
        #     return 0.0

        suspicious = False

        if protocol == 'DNS' and dst_port not in ['53', '853']:
            suspicious = True

        elif protocol == 'HTTPS' and dst_port not in ['443', '8443', '9443', '10443', '4443']:
            suspicious = True

        if not suspicious:
            return 0.0

        cache_key = "common_protocol_%s_%s_%s" % (src_ip, dst_ip, dst_port)

        if application.get(cache_key):
            return 0.0

        application.put(cache_key, True, 86400)
        return 0.75

    # def algorithm(event):  
    #     dst_port = event.get('destination_port')
    #     action = event.get('event_action')
    #     dstintfrole = event.get('destination_device_interface_role')
    #     protocol = event.get('network_protocol')
    #     key = application.get("common_protocol")

    #     if key is True:
    #         return 0.0

    #     # Trigger if type matches and destination IP is malicious
    #     if dst_port not in ['80', '443', '53', '123', '25', '8443', '9443', '8080'] and dstintfrole == 'wan' and action in ['accept', 'allow', 'permit'] and protocol in ['HTTPS', 'DNS']:
    #         application.put("common_protocol", True, 86400)
    #         return 0.75
    #     return 0.0


def clusters(event):







    """
    Store the session
    """
    return []

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    # Safely extract values with defaults
    action = event.get('event_action')
    src_ip = event.get('source_ip')
    src_port = event.get('source_port')
    dst_ip = event.get('destination_ip') 
    dst_port = event.get('destination_port') 
    dst_role = event.get('destination_device_interface_role')
    src_dev = event.get('source_device_name') 
    country = event.get('destination_country')

    message = (
        "The firewall recorded outbound network activity where traffic was {action} "
        "from {src_dev} ({src_ip}:{src_port}) to {dst_ip}:{dst_port} ."
        "The destination interface role was {dst_role}. "
        "The target IP belongs to {country}. "
        "This event was detected as external communication on a potentially uncommon port, "
        "which may indicate the use of custom or covert command-and-control channels."
    ).format(
        action=action,
        src_dev=src_dev,
        src_ip=src_ip,
        src_port=src_port,
        dst_ip=dst_ip,
        dst_port=dst_port,
        dst_role=dst_role,
        country=country
    )

    return message

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Non-Standard Port (T1571)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","network_protocol","event_action","destination_device_interface_role","destination_country"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "ipaddress"
    }
