
# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return "palo_alto_encryption_monitor"

def automate():

    # automation: palo_alto_encryption_monitor
    return True

def notify():
    return False

def algorithm(event):
    """
    Core detection logic to compute a risk score.
    stats is an implicit object providing count/sum/avg/min/max/distinct_count over window+group_by.
    Return a float 0.0 to 1.0
    """
    source_ip = event.get('source_ip')
    if not source_ip:
        return 0.0

    score = 0.0

    tls_version = _norm(event.get('tls_version'))
    key_exchange = _norm(event.get('tls_key_exchange'))
    encryption = _norm(event.get('tls_encryption'))
    hash_alg = _norm(event.get('tls_hash_algorithm'))
    root_status = _norm(event.get('tls_root_status'))
    chain_status = _norm(event.get('tls_chain_status'))
    subject_cn = _norm(event.get('tls_subject_common_name'))
    dst_port = event.get('destination_port')
    action = _norm(event.get('event_action'))
    app = _norm(event.get('applicationname'))

    # 1. Certificate trust / validation failures
    if root_status and root_status not in {'trusted', 'ok', 'valid', 'success'}:
        score += 0.35

    if chain_status and chain_status not in {'trusted', 'ok', 'valid', 'success'}:
        score += 0.30

    # 4. Weak / legacy TLS profile
    if tls_version in {'ssl', 'sslv2', 'sslv3', 'tls1.0', 'tls1.1', 'tlsv1', 'tlsv1.0', 'tlsv1.1'}:
        score += 0.20

    weak_kx = {'rsa', 'static rsa'}
    if key_exchange in weak_kx:
        score += 0.10

    weak_enc_keywords = ['rc4', '3des', 'des', 'null', 'export']
    if any(x in encryption for x in weak_enc_keywords):
        score += 0.20

    weak_hash_keywords = ['md5', 'sha1']
    if any(x in hash_alg for x in weak_hash_keywords):
        score += 0.15

    # 5. TLS on non-standard ports
    if _is_non_standard_tls_port(dst_port) and (tls_version or app in {'ssl', 'web-browsing'}):
        score += 0.10

    # 6. Stronger signal when session was allowed/succeeded
    if action in {'allow', 'alert'} and score > 0:
        score += 0.05

    return min(score, 1.0)


def clusters(event):


    return session.get("clusterss")

def context(event):
    """
    Provides a human-readable context message explaining why the detection was triggered.
    Uses event attributes to build this message.
    """
    return (
        'Suspicious TLS certificate or handshake anomaly detected from source IP '
        + str(event.get('source_ip'))
        + '. The session shows certificate validation issues, TLS mismatch indicators, '
        + 'or weak TLS characteristics that may indicate evasion, misconfiguration, or suspicious encrypted traffic.'
    )

def criticality():
    return "HIGH"

def tactic():
    return "Defense Evasion (TA0005)"

def technique():
    return "Encrypted Channel (T1573)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","tls_version","tls_key_exchange","tls_encryption","tls_hash_algorithm","tls_subject_common_name","tls_root_status","tls_chain_status","applicationname","event_action"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }


def _cn_sni_mismatch(subject_cn, sni):
    subject_cn = _norm(subject_cn)
    sni = _norm(sni)

    if not subject_cn or not sni:
        return False

    if subject_cn == sni:
        return False

    # wildcard support
    if subject_cn.startswith('*.'):
        suffix = subject_cn[1:]  # ".example.com"
        if sni.endswith(suffix):
            return False

    return True
def _is_non_standard_tls_port(port):
    try:
        p = int(port)
    except Exception:
        return False
    return p not in {443, 8443, 9443}