# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return None

def groupby():
    return []

def investigate():
    return "palo_alto_threat_intelligence"

def automate():

    # automation: palo_alto_threat_intelligence
    return True

def notify():
    return False

def algorithm(event):
    dst_ip = event.get('destination_ip')
    action = (event.get('event_action') or '').lower()

    if not dst_ip:
        return 0.0

    if action not in ['allow', 'accept', 'permit']:
        return 0.0

    malicious_ip = tpi.query('MaliciousIP', 'ip = ?', [dst_ip])

    if not malicious_ip or not malicious_ip.get('rows'):
        return 0.0

    return 0.75


def clusters(event):

    return session.get("clusterss")

def context(event):
    return (
        'Outbound connection detected from source IP '
        + str(event.get('source_ip'))
        + ' to known malicious IP '
        + str(event.get('destination_ip'))
        + '. This communication was allowed and may indicate command-and-control activity.'
    )

def criticality():
    return "HIGH"

def tactic():
    return "Command and Control (TA0011)"

def technique():
    return "Application Layer Protocol (T1071)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","network_protocol","applicationname","event_action"])

def correlationArtifacts():
    return ["destination_ip","event_action"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }
