ALLOWED_ACTIONS = {"allow", "accept", "permit"}

# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["destination_ip"]

def investigate():
    return "palo_alto_network_traffic_intelligence"

def automate():

    # automation: palo_alto_network_traffic_intelligence
    return True

def notify():
    return False

def algorithm(event):
    # Fast lock check
    try:
        if application.get("pa_inbound_connections_spike") in (True, "true", "True"):
            return 0.0
    except Exception:
        pass

    # Normalize once
    log_type = (event.get("event_type") or event.get("log_type") or "").lower()

    # Fast reject non-traffic logs
    if log_type and log_type != "traffic":
        return 0.0

    # Fast reject non-allowed actions
    action = (event.get("action") or event.get("event_action") or "").lower()
    if action not in ALLOWED_ACTIONS:
        return 0.0

    # Fast reject non inbound traffic
    if (
        (event.get("source_zone") or "").lower() != "wan" or
        (event.get("destination_zone") or "").lower() != "lan"
    ):
        return 0.0

    # Counter check
    count = stats.count("pa_inbound_connections")

    if count < 100:
        return 0.0

    # Expensive operations only after threshold
    stats.resetcount("pa_inbound_connections")

    if application.putifabsent(
        "pa_inbound_connections_spike",
        True,
        86400
    ):
        return 0.75

    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    return (
        'Spike in inbound connections detected targeting destination IP '
        + str(event_data.get('destination_ip'))
        + '. A high number of incoming connections were observed within a short time window, '
        + 'which may indicate scanning, brute-force attempts, or exploitation activity.'
    )

def criticality():
    return "HIGH"

def tactic():
    return "Initial Access (TA0001)"

def technique():
    return "Exploit Public-Facing Application (T1190)"

def artifacts():
    return stats.collect(["source_ip","destination_ip","destination_port","network_protocol","event_action"])

def correlationArtifacts():
    return ["destination_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("destination_ip", "unknown"),
        "type": "ipaddress"
    }

