# Auto-generated by BinaryFlux UI Builder
# New Detection (new_detection) v1.0.0


def init(event):
    """
    Use appropriate ueba method
    """
    """
    Use appropriate ueba method
    """
    return "initialization completed"

def window():
    return "5m"

def groupby():
    return ["source_ip"]

def investigate():
    return "palo_alto_authentication_monitor"

def automate():

    # automation: palo_alto_authentication_monitor
    return True

def notify():
    return False

def algorithm(event):
    message = ' '.join([
        str(event.get('event_action') or ''),
        str(event.get('policy_name') or ''),
        str(event.get('descriptions') or '')
    ]).lower()
    src_ip = event.get('source_ip')

    if not message or not src_ip:
        return 0.0

    if any(indicator in message for indicator in [
        'login failed',
        'authentication failed',
        'invalid user',
        'failed password',
        'bad credentials'
    ]):
        count = stats.count('failed_login_attempts')
        if count >= 5:
            stats.resetcount('failed_login_attempts')
            return 0.75

    return 0.0


def clusters(event):


    return session.get("clusterss")

def context(event):
    return (
        'Multiple failed login attempts detected from source IP '
        + str(event.get('source_ip'))
        + ' within a time window of 5-minutes. This pattern indicates a possible brute-force attack '
        + 'attempting to gain unauthorized access.'
    )

def criticality():
    return "HIGH"

def tactic():
    return "Credential Access (TA0006)"

def technique():
    return "Brute Force (T1110)"

def artifacts():
    return stats.collect(["source_ip","policy_name","useragent","user_name","event_action"])

def correlationArtifacts():
    return ["source_ip"]

def entity(event):
    return {
        "derived": False,
        "value": event.get("source_ip", "unknown"),
        "type": "email"
    }
